'use strict';
const cfg=window.BAUER_CONFIG||{};const $=id=>document.getElementById(id);const p=new URLSearchParams(location.search);const type=p.get('type');const id=p.get('id');const contact=p.get('contact');const archive=p.get('archive');let db=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function notice(t,type=''){const n=$('notice');n.textContent=t;n.className=`notice ${type}`.trim();}
function fact(label,value){return `<div class="fact"><label>${esc(label)}</label><div>${esc(value||'—')}</div></div>`;}
function dateLabel(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString();}
function back(){if(contact)location.href=`contacts.html?contact=${encodeURIComponent(contact)}`;else if(archive)location.href=`contacts.html?archive=${encodeURIComponent(archive)}`;else location.href='contacts.html';}
function relatedLink(href,title,meta){return `<a class="related" href="${href}"><b>${esc(title)}</b><div class="sub">${esc(meta||'')}</div></a>`;}
async function loadInquiry(){const r=await db.from('marketsharp_inquiries').select('*').eq('marketsharp_lead_id',id).single();if(r.error)return notice(r.error.message,'error');const x=r.data;$('title').textContent=`Archived Inquiry${x.bauer_lead_number?` #${x.bauer_lead_number}`:''}`;$('subtitle').textContent='Original preserved MarketSharp inquiry';$('facts').innerHTML=[fact('Inquiry date',dateLabel(x.inquiry_date_text)),fact('Inquiry number',x.bauer_lead_number),fact('Source',x.source),fact('Description',x.description),fact('Property address',[x.property_address,x.property_address_line_two,x.city,x.state,x.zip].filter(Boolean).join(', ')),fact('Appointments',x.appointment_count),fact('Jobs',x.job_count),fact('Notes',x.notes),fact('Migration class',x.migration_class),fact('Promotion status',x.promotion_status)].join('');$('rawData').textContent=JSON.stringify(x.raw_data||{},null,2);if(x.operations_lead_id){$('broBtn').style.display='inline-flex';$('broBtn').href=`inquiry.html?id=${encodeURIComponent(x.operations_lead_id)}${contact?`&contact=${encodeURIComponent(contact)}`:''}`;}
const [a,j]=await Promise.all([db.from('marketsharp_appointments').select('*').eq('marketsharp_lead_id',x.marketsharp_lead_id).order('appointment_date_text',{ascending:false}),db.from('marketsharp_jobs').select('*').eq('marketsharp_lead_id',x.marketsharp_lead_id).order('sale_date_text',{ascending:false})]);const links=[];(a.data||[]).forEach(v=>links.push(`<div class="related"><b>Appointment — ${esc(dateLabel(v.appointment_date_text))}</b><div class="sub">${esc([v.appointment_type,v.appointment_result].filter(Boolean).join(' • '))}</div></div>`));(j.data||[]).forEach(v=>links.push(relatedLink(`archive-record.html?type=job&id=${encodeURIComponent(v.marketsharp_job_id)}${contact?`&contact=${encodeURIComponent(contact)}`:''}&archive=${encodeURIComponent(v.marketsharp_contact_id||archive||'')}`,`Job ${v.job_number||v.job_name||''}`,[v.job_type,v.job_status].filter(Boolean).join(' • '))));if(links.length){$('relatedSection').style.display='block';$('related').innerHTML=links.join('');}}
async function loadJob(){const r=await db.from('marketsharp_jobs').select('*').eq('marketsharp_job_id',id).single();if(r.error)return notice(r.error.message,'error');const x=r.data;$('title').textContent=`Archived Job ${x.job_number||''}`;$('subtitle').textContent='Original preserved MarketSharp job';$('facts').innerHTML=[fact('Job number',x.job_number),fact('Job name',x.job_name),fact('Job type',x.job_type),fact('Status',x.job_status),fact('Sale date',dateLabel(x.sale_date_text)),fact('Start date',dateLabel(x.start_date_text)),fact('Address',[x.address_line_one,x.address_line_two,x.city,x.state,x.zip].filter(Boolean).join(', ')),fact('Description',x.job_description),fact('Notes',x.notes),fact('Was active in MarketSharp',x.is_active===true?'Yes':x.is_active===false?'No':'—')].join('');$('rawData').textContent=JSON.stringify(x.raw_data||{},null,2);if(x.operations_job_id){$('broBtn').style.display='inline-flex';$('broBtn').href=`jobs.html?job=${encodeURIComponent(x.operations_job_id)}`;}if(x.marketsharp_lead_id){$('relatedSection').style.display='block';$('related').innerHTML=relatedLink(`archive-record.html?type=inquiry&id=${encodeURIComponent(x.marketsharp_lead_id)}${contact?`&contact=${encodeURIComponent(contact)}`:''}&archive=${encodeURIComponent(x.marketsharp_contact_id||archive||'')}`,'Open related archived inquiry','Preserved inquiry record');}}
async function start(){db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const {data}=await db.auth.getSession();if(!data.session){location.href='index.html';return;}if(type==='inquiry')await loadInquiry();else if(type==='job')await loadJob();else notice('No archived record was selected.','error');}
$('backBtn').onclick=back;start();