'use strict';
function broJobType(j){const candidates=[j.job_type,j.primary_category,j.primary_job_type];return candidates.map(v=>String(v||'').trim()).find(v=>v&&!/^\d{2}[a-z]\d{4}$/i.test(v))||'Needs type review';}
function broJobStage(j){return String(j.stage||'').trim()==='Needs Production Review'?'Awarded':(j.stage||'');}

const cfg=window.BAUER_CONFIG||{};const $=id=>document.getElementById(id);let db=null;let session=null;let selected=null;let searchTimer=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function notice(t,type=''){const n=$('notice');n.textContent=t;n.className=`notice ${type}`.trim();}
function dateLabel(v){if(!v)return'—';const raw=String(v);const d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(raw)?raw+'T12:00:00':raw);return Number.isNaN(d.getTime())?raw:d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function phoneDigits(v){return String(v||'').replace(/\D/g,'');}
function itemLink(href,body){return `<a class="history-item" style="display:block;color:inherit;text-decoration:none;cursor:pointer" href="${href}">${body}</a>`;}
function inquiryBody(l,right='→'){return `<div class="history-grid"><div><b>Inquiry #${esc(l.lead_number??l.bauer_lead_number??'')}</b><div class="result-meta">${esc(dateLabel(l.lead_date||l.inquiry_at||l.inquiry_date_text||l.created_at))}</div></div><div><b>${esc(l.product_interest||l.work_category||l.source||'Inquiry')}</b><div>${esc(l.street_address||l.property_address||'')}</div><div class="result-meta">${esc(l.product_description||l.description||l.notes||'')}</div></div><div>${esc(right)}</div></div>`;}
function jobBody(j,right='→'){return `<div class="history-grid"><div><b>Job ${esc(j.job_number||'')}</b><div class="result-meta">${esc(dateLabel(j.contract_date||j.sale_date||j.sale_date_text||j.start_date_text||j.created_at))}</div></div><div><b>${esc(broJobType(j))}</b><div>${esc(j.property_address||j.address_line_one||'')}</div><div class="result-meta">${esc(j.production_notes||j.job_description||j.notes||'')}</div></div><div>${esc(right)}</div></div>`;}
async function searchContacts(){const q=String($('contactSearchInput').value||'').trim();$('contactDetail').classList.add('hidden');if(!q){$('searchResults').innerHTML='<div class="empty-state">Start typing a name, address, phone number, inquiry number, job number, email, or other detail.</div>';return;}$('searchResults').innerHTML='<div class="empty-state">Searching…</div>';const {data,error}=await db.rpc('bauer_contact_search',{p_query:q});if(error){notice(error.message,'error');$('searchResults').innerHTML='<div class="empty-state">Search could not be completed.</div>';return;}const rows=data||[];$('searchResults').innerHTML=rows.length?rows.map((r,i)=>`<button class="result" type="button" data-result-index="${i}"><div><div class="result-name">${esc(r.display_name)}${r.source_type==='MarketSharp Archive'?'<span class="archive-badge">Older history</span>':''}</div><div class="result-meta">${esc(r.context_summary||'')}</div></div><div><div>${esc(r.phone||'')}</div><div class="result-meta">${esc(r.email||'')}</div></div><div><div>${esc([r.street_address,r.city,r.state,r.zip].filter(Boolean).join(', '))}</div><div class="result-meta">${esc(r.source_type==='BRO'?'Bauer Roofing Operations':'Preserved MarketSharp history')}</div></div></button>`).join(''):'<div class="empty-state">No contacts matched that search.</div>';$('searchResults').querySelectorAll('[data-result-index]').forEach(b=>b.onclick=()=>openResult(rows[Number(b.dataset.resultIndex)]));}
async function openResult(r){selected=r;if(r.source_type==='BRO')await openBroContact(r.contact_id);else await openArchiveContact(r.marketsharp_contact_id);}
function contactHeader(c,label,extra=''){return `<div class="detail-head"><div><h2>${esc(c.name)}</h2><div class="sub">${esc(label)}</div></div><div class="detail-actions">${extra}<button class="btn primary" type="button" id="detailInquiryBtn">+ Inquiry</button></div></div><div class="contact-facts"><div class="fact"><label>Phone</label><div>${c.phone?`<a href="tel:${esc(phoneDigits(c.phone))}">${esc(c.phone)}</a>`:'—'}</div></div><div class="fact"><label>Email</label><div>${c.email?`<a href="mailto:${esc(c.email)}">${esc(c.email)}</a>`:'—'}</div></div><div class="fact"><label>Address</label><div>${esc([c.street_address,c.city,c.state,c.zip].filter(Boolean).join(', ')||'—')}</div></div><div class="fact"><label>Notes</label><div>${esc(c.notes||'—')}</div></div></div>`;}
async function openBroContact(id){
  const [cRes,lRes,msRes]=await Promise.all([
    db.from('contacts').select('*').eq('id',id).single(),
    db.from('leads').select('*').eq('contact_id',id).is('deleted_at',null).order('created_at',{ascending:false}),
    db.from('marketsharp_contacts').select('marketsharp_contact_id').eq('operations_contact_id',id)
  ]);
  if(cRes.error)return notice(cRes.error.message,'error');
  if(lRes.error)return notice(lRes.error.message,'error');
  const c=cRes.data,leads=lRes.data||[];
  const jobQueries=[db.from('jobs').select('*').eq('customer_id',id).is('deleted_at',null)];
  const leadIds=leads.map(l=>l.id).filter(Boolean);
  const leadNumbers=[...new Set(leads.map(l=>String(l.lead_number||'').trim()).filter(Boolean))];
  if(leadIds.length)jobQueries.push(db.from('jobs').select('*').in('lead_id',leadIds).is('deleted_at',null));
  if(leadNumbers.length)jobQueries.push(db.from('jobs').select('*').in('lead_number',leadNumbers).is('deleted_at',null));
  const jobResults=await Promise.all(jobQueries);
  const jobError=jobResults.find(r=>r.error)?.error;
  if(jobError)return notice(jobError.message,'error');
  const jobs=[...new Map(jobResults.flatMap(r=>r.data||[]).map(j=>[j.id,j])).values()]
    .sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));
  const msIds=(msRes.data||[]).map(x=>x.marketsharp_contact_id);
  let msLeads=[],msJobs=[];
  if(msIds.length){
    const [ml,mj]=await Promise.all([
      db.from('marketsharp_inquiries').select('*').in('marketsharp_contact_id',msIds).order('inquiry_date_text',{ascending:false}),
      db.from('marketsharp_jobs').select('*').in('marketsharp_contact_id',msIds).order('sale_date_text',{ascending:false})
    ]);
    msLeads=ml.data||[];msJobs=mj.data||[];
  }
  selected={source_type:'BRO',contact_id:id,display_name:c.name};
  const leadHtml=leads.length?leads.map(l=>itemLink(`inquiry.html?id=${encodeURIComponent(l.id)}&contact=${encodeURIComponent(id)}`,inquiryBody(l,l.lead_status||l.status||'Open →'))).join(''):'<div class="empty-state">No current BRO inquiries.</div>';
  const jobHtml=jobs.length?jobs.map(j=>itemLink(`jobs.html?job=${encodeURIComponent(j.id)}`,jobBody(j,broJobStage(j)+' →'))).join(''):'<div class="empty-state">No current BRO jobs.</div>';
  const archivedLeadHtml=msLeads.length?msLeads.map(l=>itemLink(`archive-record.html?type=inquiry&id=${encodeURIComponent(l.marketsharp_lead_id)}&contact=${encodeURIComponent(id)}&archive=${encodeURIComponent(l.marketsharp_contact_id)}`,inquiryBody(l,'Preserved history →'))).join(''):'<div class="empty-state">No preserved inquiries linked to this contact.</div>';
  const archivedJobHtml=msJobs.length?msJobs.map(j=>itemLink(`archive-record.html?type=job&id=${encodeURIComponent(j.marketsharp_job_id)}&contact=${encodeURIComponent(id)}&archive=${encodeURIComponent(j.marketsharp_contact_id)}`,jobBody(j,'Preserved history →'))).join(''):'<div class="empty-state">No preserved jobs linked to this contact.</div>';
  const detail=$('contactDetail');
  detail.innerHTML=contactHeader(c,'Bauer Roofing Operations')+`<div class="history-section current-inquiries-section"><h3>Inquiries</h3>${leadHtml}</div><div class="history-section current-jobs-section"><h3>Jobs</h3>${jobHtml}</div>${msIds.length?`<div class="history-section archived-history-section"><h3>Preserved MarketSharp History</h3><div class="result-meta">These are the original archived records and remain available even when a BRO record also exists.</div><h4>Archived Inquiries</h4>${archivedLeadHtml}<h4>Archived Jobs</h4>${archivedJobHtml}</div>`:''}`;
  detail.classList.remove('hidden');
  $('detailInquiryBtn').onclick=()=>fillInquiry(c);
  detail.scrollIntoView({behavior:'smooth',block:'start'});
}
async function openArchiveContact(msId){const [cRes,lRes,jRes]=await Promise.all([db.from('marketsharp_contacts').select('*').eq('marketsharp_contact_id',msId).single(),db.from('marketsharp_inquiries').select('*').eq('marketsharp_contact_id',msId).order('inquiry_date_text',{ascending:false}),db.from('marketsharp_jobs').select('*').eq('marketsharp_contact_id',msId).order('sale_date_text',{ascending:false})]);if(cRes.error)return notice(cRes.error.message,'error');const m=cRes.data,name=String(m.business_name||'').trim()||[m.first_name,m.last_name].filter(Boolean).join(' ').trim()||'Unnamed contact',c={name,phone:m.phone,email:m.primary_email,street_address:m.address_line_one,city:m.city,state:m.state,zip:m.zip,notes:'Preserved MarketSharp contact.'};selected={source_type:'MarketSharp Archive',marketsharp_contact_id:msId,display_name:name};const leads=lRes.data||[],jobs=jRes.data||[];const leadHtml=leads.length?leads.map(l=>itemLink(`archive-record.html?type=inquiry&id=${encodeURIComponent(l.marketsharp_lead_id)}&archive=${encodeURIComponent(msId)}${m.operations_contact_id?`&contact=${encodeURIComponent(m.operations_contact_id)}`:''}`,inquiryBody(l,l.operations_lead_id?'Also linked to BRO →':'Archived history →'))).join(''):'<div class="empty-state">No archived inquiries.</div>';const jobHtml=jobs.length?jobs.map(j=>itemLink(`archive-record.html?type=job&id=${encodeURIComponent(j.marketsharp_job_id)}&archive=${encodeURIComponent(msId)}${m.operations_contact_id?`&contact=${encodeURIComponent(m.operations_contact_id)}`:''}`,jobBody(j,j.operations_job_id?'Also linked to BRO →':'Archived history →'))).join(''):'<div class="empty-state">No archived jobs.</div>';const extra=m.operations_contact_id?`<a class="btn" href="contacts.html?contact=${encodeURIComponent(m.operations_contact_id)}">Open Current BRO Contact</a>`:'';const detail=$('contactDetail');detail.innerHTML=contactHeader(c,'Preserved MarketSharp history',extra)+`<div class="history-section"><h3>Archived Inquiries</h3>${leadHtml}</div><div class="history-section"><h3>Archived Jobs</h3>${jobHtml}</div>`;detail.classList.remove('hidden');$('detailInquiryBtn').onclick=async()=>{if(m.operations_contact_id){const r=await db.from('contacts').select('*').eq('id',m.operations_contact_id).single();if(!r.error)return fillInquiry(r.data);}await promoteArchiveAndOpenInquiry(m,c);};detail.scrollIntoView({behavior:'smooth',block:'start'});}
function fillInquiry(c){$('inquiryContactId').value=c.id;$('inquiryContactName').value=c.name;$('inquiryAddress').value=c.street_address||'';$('inquiryLeadNumber').value='';$('inquirySource').value='';$('inquiryWorkCategory').value='Roofing';$('inquiryAssigned').value='Roy';$('inquiryNotes').value='';$('inquiryDialog').showModal();}
async function promoteArchiveAndOpenInquiry(ms,c){const ins=await db.from('contacts').insert({name:c.name,phone:c.phone||null,email:c.email||null,street_address:c.street_address||null,city:c.city||null,state:c.state||null,zip:c.zip||null,notes:`Created from preserved MarketSharp contact ${ms.marketsharp_contact_id} when new work was requested.`}).select('*').single();if(ins.error)return notice(ins.error.message,'error');const link=await db.from('marketsharp_contacts').update({operations_contact_id:ins.data.id,updated_at:new Date().toISOString()}).eq('marketsharp_contact_id',ms.marketsharp_contact_id);if(link.error)return notice(`Contact was created but archive link failed: ${link.error.message}`,'error');fillInquiry(ins.data);}
async function saveNewContact(){const name=String($('newContactName').value||'').trim();if(!name)return notice('Name or company is required.','error');const row={name,phone:$('newContactPhone').value.trim()||null,email:$('newContactEmail').value.trim()||null,street_address:$('newContactStreet').value.trim()||null,city:$('newContactCity').value.trim()||null,state:$('newContactState').value.trim()||null,zip:$('newContactZip').value.trim()||null,notes:$('newContactNotes').value.trim()||null};const {data,error}=await db.from('contacts').insert(row).select('*').single();if(error)return notice(error.message,'error');$('contactDialog').close();$('contactSearchInput').value=data.name;await searchContacts();await openBroContact(data.id);notice('Contact added.','success');}
async function saveInquiry(){const cid=$('inquiryContactId').value,r=await db.from('contacts').select('*').eq('id',cid).single();if(r.error)return notice(r.error.message,'error');const c=r.data,row={contact_id:c.id,lead_number:$('inquiryLeadNumber').value.trim()||null,homeowner_name:c.name,street_address:$('inquiryAddress').value.trim()||c.street_address||null,phone:c.phone||null,email:c.email||null,source:$('inquirySource').value.trim()||null,import_source:'Contact Inquiry',work_category:$('inquiryWorkCategory').value,lead_status:'Appointment Wanted',assigned_to:$('inquiryAssigned').value.trim()||'Roy',notes:$('inquiryNotes').value.trim()||null,lead_date:new Date().toLocaleDateString('en-CA')};const {data,error}=await db.from('leads').insert(row).select('*').single();if(error)return notice(error.message,'error');$('inquiryDialog').close();location.href=`inquiry.html?id=${encodeURIComponent(data.id)}&contact=${encodeURIComponent(c.id)}`;}
async function start(){if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)return notice('Database configuration is missing.','error');db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const auth=await db.auth.getSession();session=auth.data.session;if(!session){location.href='index.html';return;}const p=new URLSearchParams(location.search),cid=p.get('contact'),aid=p.get('archive');if(cid)await openBroContact(cid);else if(aid)await openArchiveContact(aid);else $('contactSearchInput').focus();}
$('contactSearchBtn').onclick=searchContacts;$('contactSearchInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchContacts();}});$('contactSearchInput').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if($('contactSearchInput').value.trim().length>=2)searchContacts();},300);});$('addContactBtn').onclick=()=>{$('newContactName').value='';$('newContactPhone').value='';$('newContactEmail').value='';$('newContactStreet').value='';$('newContactCity').value='';$('newContactState').value='SC';$('newContactZip').value='';$('newContactNotes').value='';$('contactDialog').showModal();};$('saveNewContactBtn').onclick=saveNewContact;$('saveInquiryBtn').onclick=saveInquiry;start();
