'use strict';
(function(){
 const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;
 let dialog,preview,status,start,insert,recognition,target,original,from,to;
 const fallback=/Windows/i.test(navigator.userAgent)?'Click in the text field, then press Windows + H to dictate.':'Use the microphone on your device’s keyboard or its built-in Dictation feature.';
 function stop(){if(recognition){const r=recognition;recognition=null;r.onresult=null;r.onend=null;r.onerror=null;try{r.abort();}catch{}}if(start)start.textContent='🎙 Start dictation';}
 function setup(){if(dialog)return;dialog=document.createElement('dialog');dialog.className='bro-dictation';dialog.dataset.noDictation='true';dialog.innerHTML='<div style="padding:20px"><h2>Dictate text</h2><p>Speak, review the words, then insert them into your field. Save the form when you are ready.</p><p class="bro-dictation-help">Your browser may process speech online. BRO does not store audio.</p><textarea aria-label="Dictated text to review" rows="6"></textarea><p role="status" aria-live="polite"></p><div class="bro-dictation-actions"><button type="button" class="btn">🎙 Start dictation</button><button type="button" class="btn primary">Insert text</button><button type="button" class="btn">Cancel</button></div></div>';document.body.append(dialog);
 preview=dialog.querySelector('textarea');status=dialog.querySelector('[role=status]');[start,insert]=dialog.querySelectorAll('button');start.onclick=()=>{if(recognition){stop();status.textContent='Stopped. Review the text below.';return;}if(!Speech){status.textContent=fallback;return;}const r=new Speech();recognition=r;r.lang='en-US';r.continuous=true;r.interimResults=false;r.onresult=e=>{if(recognition!==r)return;for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal){const words=e.results[i][0].transcript.trim();preview.value+=(preview.value&&!/\s$/.test(preview.value)?' ':'')+words;}status.textContent='Listening… You can stop and review at any time.';};r.onerror=e=>{if(recognition!==r)return;status.textContent=({ 'not-allowed':'Microphone access was not allowed. Enable it in your browser settings, or use device dictation.','audio-capture':'No microphone is available. Check that it is connected.','no-speech':'No speech was heard. Try again when ready.','network':'Speech recognition could not connect. '+fallback,'service-not-allowed':fallback })[e.error]||'Dictation stopped. '+fallback;stop();};r.onend=()=>{if(recognition!==r)return;recognition=null;start.textContent='🎙 Start dictation';status.textContent='Finished listening. Review your words before inserting.';};try{r.start();start.textContent='■ Stop dictation';status.textContent='Listening…';}catch{stop();status.textContent=fallback;}};
 insert.onclick=()=>{stop();if(!target?.isConnected||target.disabled||target.readOnly||target.value!==original){status.textContent='The original field changed. Close this window and start again to avoid replacing your edits.';return;}const words=preview.value.trim();if(!words){status.textContent='Dictate or type some text first.';return;}const left=original.slice(0,from),right=original.slice(to);const addition=(left&&!/\s$/.test(left)?' ':'')+words+(right&&!/^\s/.test(right)?' ':'');const value=left+addition+right;if(target.maxLength>=0&&value.length>target.maxLength){status.textContent='This text exceeds the field’s limit. Shorten it before inserting.';return;}target.value=value;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}));dialog.close();target.focus();target.setSelectionRange(left.length+addition.length,left.length+addition.length);};dialog.querySelector('button:last-child').onclick=()=>dialog.close();dialog.addEventListener('close',stop);dialog.addEventListener('cancel',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});}
 function open(field){setup();stop();target=field;original=field.value;from=field.selectionStart??original.length;to=field.selectionEnd??from;preview.value='';status.textContent=Speech?'Press Start dictation when ready.':fallback;start.disabled=!Speech;dialog.showModal();}
 function scan(){document.querySelectorAll('textarea,input[type=text],input:not([type])').forEach(field=>{if(field.dataset.broDictation||field.closest('[data-no-dictation],#authView,#loginView')||field.readOnly||field.disabled||field.type==='password'||/password|token|secret/i.test(field.id+' '+field.name)||['decimal','numeric','email','url','tel'].includes(field.inputMode))return;field.dataset.broDictation='true';const button=document.createElement('button');button.type='button';button.className='btn bro-dictate-button';button.textContent='🎙 Dictate';const label=field.labels?.[0]?.textContent.trim()||field.placeholder||'text';button.setAttribute('aria-label','Dictate '+label);button.addEventListener('click',()=>open(field));field.after(button);});}
 const style=document.createElement('style');style.textContent='.bro-dictate-button{display:inline-flex;align-items:center;min-height:36px;margin:5px 0 8px!important;padding:6px 10px!important;font-size:13px!important;color:#245998;background:#edf4ff;border:1px solid #cadbf1;border-radius:8px}.bro-dictation{width:min(560px,calc(100vw - 24px));max-height:90dvh;overflow:auto;border:1px solid #cbd5e1;border-radius:14px;padding:0}.bro-dictation textarea{box-sizing:border-box;width:100%;font-size:16px}.bro-dictation-actions{display:flex;flex-wrap:wrap;gap:8px}.bro-dictation-help{font-size:12px;color:#526078}.bro-dictation::backdrop{background:#172c4666}@media print{.bro-dictate-button,.bro-dictation{display:none!important}}';document.head.append(style);
 let queued=false;function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;scan();});}new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});scan();
})();
