'use strict';
const cfg=window.BAUER_CONFIG||{};const $=id=>document.getElementById(id);let db=null;let inquiry=null;let appointments=[];let linkedJob=null;let resolvedContactId='';const params=new URLSearchParams(location.search);const inquiryId=params.get('id');const requestedContactId=params.get('contact');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function notice(t,type=''){const n=$('notice');n.textContent=t;n.className=`notice ${type}`.trim();}
function localInput(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function dateTimeLabel(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString();}
function norm(v){return String(v||'').trim().toLowerCase();}
function phoneDigits(v){return String(v||'').replace(/\D/g,'');}
function exactContactId(){return inquiry?.contact_id||requestedContactId||linkedJob?.customer_id||resolvedContactId||'';}
async function resolveContactId(){const known=exactContactId();if(known)return known;if(!inquiry)return'';const query=inquiry.email||inquiry.phone||inquiry.homeowner_name||'';if(!query)return'';const {data,error}=await db.rpc('bauer_contact_search',{p_query:query});if(error)return'';const rows=(data||[]).filter(r=>r.source_type==='BRO'&&r.contact_id);const exact=rows.filter(r=>{const emailMatch=inquiry.email&&r.email&&norm(inquiry.email)===norm(r.email);const phoneMatch=inquiry.phone&&r.phone&&phoneDigits(inquiry.phone)===phoneDigits(r.phone);const nameMatch=inquiry.homeowner_name&&r.display_name&&norm(inquiry.homeowner_name)===norm(r.display_name);const streetMatch=inquiry.street_address&&r.street_address&&norm(inquiry.street_address)===norm(r.street_address);return emailMatch||phoneMatch||(nameMatch&&streetMatch);});if(exact.length===1){resolvedContactId=exact[0].contact_id;await db.from('leads').update({contact_id:resolvedContactId,updated_at:new Date().toISOString()}).eq('id',inquiryId);inquiry.contact_id=resolvedContactId;return resolvedContactId;}if(rows.length===1&&norm(rows[0].display_name)===norm(inquiry.homeowner_name)){resolvedContactId=rows[0].contact_id;return resolvedContactId;}return'';}
async function goToContact(){const cid=await resolveContactId();if(cid)location.href=`contacts.html?contact=${encodeURIComponent(cid)}`;else location.href=`contacts.html`;}
function fill(){if(!inquiry)return;$('title').textContent=`Inquiry #${inquiry.lead_number||''}`;$('subtitle').textContent=inquiry.homeowner_name||'';$('leadNumber').value=inquiry.lead_number||'';$('inquiryAt').value=localInput(inquiry.inquiry_at||inquiry.received_at);$('takenBy').value=inquiry.inquiry_taken_by||inquiry.taken_by||'';$('assignedTo').value=inquiry.assigned_to||inquiry.salesperson||'';$('source').value=inquiry.source||'';$('sourceSecondary').value=inquiry.lead_source_secondary||'';$('productInterest').value=inquiry.product_interest||'';$('productDescription').value=inquiry.product_description||'';$('workCategory').value=inquiry.work_category||'';$('phone').value=inquiry.phone||'';$('email').value=inquiry.email||'';$('address').value=inquiry.street_address||'';$('city').value=inquiry.city||'';$('state').value=inquiry.state||'';$('zip').value=inquiry.zip||'';$('notes').value=inquiry.notes||'';}
function renderAppointments(){const box=$('appointmentList');box.innerHTML=appointments.length?appointments.map(a=>`<div class="appt" data-appt-id="${esc(a.id)}"><div class="appt-grid"><div><b>${esc(dateTimeLabel(a.appointment_at))}</b><div class="sub">${esc(a.appointment_type||'Appointment')}</div></div><div><b>${esc(a.assigned_to||'')}</b><div>${esc(a.notes||'')}</div></div><div>${esc(a.appointment_result||a.appointment_status||'')}</div></div></div>`).join(''):'<div class="empty">No appointments yet.</div>';box.querySelectorAll('[data-appt-id]').forEach(el=>el.onclick=()=>openAppointment(appointments.find(a=>a.id===el.dataset.apptId)));}
function openAppointment(a=null){const x=a||{};$('appointmentTitle').textContent=a?'Edit Appointment':'Add Appointment';$('appointmentId').value=x.id||'';$('appointmentAt').value=localInput(x.appointment_at);$('appointmentAssigned').value=x.assigned_to||inquiry?.assigned_to||'Roy';$('appointmentType').value=x.appointment_type||'';$('appointmentResult').value=x.appointment_result||'';$('appointmentResultNote').value=x.appointment_result_note||'';$('appointmentNotes').value=x.notes||'';$('appointmentDialog').showModal();}
async function saveInquiry(){const patch={lead_number:$('leadNumber').value.trim()||null,inquiry_at:$('inquiryAt').value?new Date($('inquiryAt').value).toISOString():null,inquiry_taken_by:$('takenBy').value.trim()||null,assigned_to:$('assignedTo').value.trim()||null,source:$('source').value.trim()||null,lead_source_secondary:$('sourceSecondary').value.trim()||null,product_interest:$('productInterest').value.trim()||null,product_description:$('productDescription').value.trim()||null,work_category:$('workCategory').value.trim()||null,phone:$('phone').value.trim()||null,email:$('email').value.trim()||null,street_address:$('address').value.trim()||null,city:$('city').value.trim()||null,state:$('state').value.trim()||null,zip:$('zip').value.trim()||null,notes:$('notes').value.trim()||null,updated_at:new Date().toISOString()};const {data,error}=await db.from('leads').update(patch).eq('id',inquiryId).select('*').single();if(error)return notice(error.message,'error');inquiry=data;fill();notice('Inquiry updated.','success');}
async function saveAppointment(){const id=$('appointmentId').value;const row={lead_id:inquiryId,appointment_at:$('appointmentAt').value?new Date($('appointmentAt').value).toISOString():null,assigned_to:$('appointmentAssigned').value.trim()||null,appointment_type:$('appointmentType').value.trim()||null,appointment_result:$('appointmentResult').value.trim()||null,appointment_result_note:$('appointmentResultNote').value.trim()||null,notes:$('appointmentNotes').value.trim()||null,updated_at:new Date().toISOString()};let res;if(id)res=await db.from('appointments').update(row).eq('id',id).select('*').single();else res=await db.from('appointments').insert(row).select('*').single();if(res.error)return notice(res.error.message,'error');if(id)appointments=appointments.map(a=>a.id===id?res.data:a);else appointments.unshift(res.data);$('appointmentDialog').close();renderAppointments();notice(id?'Appointment updated.':'Appointment added.','success');}
function installContextMenu(){if($('inquiryContext'))return;const style=document.createElement('style');style.textContent='.inquiry-ctx{position:fixed;z-index:6000;min-width:220px;background:#fff;border:1px solid #cfd8e3;border-radius:9px;box-shadow:0 10px 28px rgba(20,35,55,.18);padding:5px;display:none}.inquiry-ctx button{display:block;width:100%;border:0;background:#fff;text-align:left;padding:8px 9px;border-radius:6px;cursor:pointer}.inquiry-ctx button:hover{background:#eef4fb}';document.head.appendChild(style);const menu=document.createElement('div');menu.id='inquiryContext';menu.className='inquiry-ctx';document.body.appendChild(menu);}
function hideContext(){const m=$('inquiryContext');if(m)m.style.display='none';}
function showContext(e,appt=null){const m=$('inquiryContext');if(!m||!inquiry)return;const items=[];if(appt)items.push(['Edit appointment',()=>openAppointment(appt)]);items.push(['Back to this contact',()=>goToContact()]);if(inquiry.phone)items.push(['Call customer',()=>location.href=`tel:${inquiry.phone}`],['Text customer',()=>location.href=`sms:${inquiry.phone}`]);if(inquiry.email)items.push(['Email customer',()=>location.href=`mailto:${inquiry.email}`]);if(!appt)items.push(['Add appointment',()=>openAppointment()],['Save inquiry',()=>saveInquiry()]);if(linkedJob)items.push(['Open job',()=>location.href=`jobs.html?job=${encodeURIComponent(linkedJob.id)}`]);items.push(['Copy inquiry number',()=>navigator.clipboard?.writeText(inquiry.lead_number||'')],['Copy address',()=>navigator.clipboard?.writeText([inquiry.street_address,inquiry.city,inquiry.state,inquiry.zip].filter(Boolean).join(', '))]);m.innerHTML=items.map((x,i)=>`<button type="button" data-mi="${i}">${esc(x[0])}</button>`).join('');m.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{hideContext();items[i][1]();});m.style.display='block';requestAnimationFrame(()=>{const r=m.getBoundingClientRect();m.style.left=Math.max(8,Math.min(e.clientX,innerWidth-r.width-8))+'px';m.style.top=Math.max(8,Math.min(e.clientY,innerHeight-r.height-8))+'px';});}
async function load(){if(!inquiryId)return notice('No inquiry was selected.','error');const [iRes,aRes,jRes]=await Promise.all([db.from('leads').select('*').eq('id',inquiryId).single(),db.from('appointments').select('*').eq('lead_id',inquiryId).is('deleted_at',null).order('appointment_at',{ascending:false}),db.from('jobs').select('*').eq('lead_id',inquiryId).is('deleted_at',null).order('created_at',{ascending:false}).limit(1)]);if(iRes.error)return notice(iRes.error.message,'error');inquiry=iRes.data;appointments=aRes.data||[];linkedJob=(jRes.data||[])[0]||null;fill();renderAppointments();if(linkedJob){$('jobBtn').style.display='inline-flex';$('jobBtn').onclick=()=>location.href=`jobs.html?job=${encodeURIComponent(linkedJob.id)}`;}if(!exactContactId())resolveContactId();}
async function start(){installContextMenu();db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const {data}=await db.auth.getSession();if(!data.session){location.href='index.html';return;}await load();}
$('saveInquiryBtn').onclick=saveInquiry;$('addAppointmentBtn').onclick=()=>openAppointment();$('saveAppointmentBtn').onclick=saveAppointment;$('backBtn').onclick=goToContact;document.addEventListener('click',e=>{if(!e.target.closest('#inquiryContext'))hideContext();});document.addEventListener('contextmenu',e=>{const apptEl=e.target.closest('[data-appt-id]');const inPage=e.target.closest('.shell');if(!inPage)return;e.preventDefault();const appt=apptEl?appointments.find(a=>a.id===apptEl.dataset.apptId):null;showContext(e,appt);});document.addEventListener('keydown',e=>{if(e.key==='Escape')hideContext();});start();