'use strict';
const cfg=window.BAUER_CONFIG||{};const $=id=>document.getElementById(id);let db=null;let jobs=[];let activeView='timeline';let weekStart=startOfWeek(new Date());
const STAGES=[['awarded','Awarded'],['contract','Contract / Deposit'],['material','Material Ordered'],['ready','Ready to Schedule'],['scheduled','Scheduled'],['delivered','Material Delivered'],['production','In Production'],['complete','Work Complete'],['closeout','Final Payment / Closeout']];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function notice(t,type=''){const n=$('notice');n.textContent=t;n.className=`notice ${type}`.trim();}
function iso(v){return String(v||'').slice(0,10)}function dateLabel(v){if(!v)return '—';const d=new Date(String(v).slice(0,10)+'T12:00:00');return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}function startOfWeek(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-x.getDay());return x;}function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x;}function sameDay(a,b){return iso(a)===iso(b.toLocaleDateString('en-CA'));}
function jobType(j){return j.job_type||j.primary_category||'Job';}
function stageKey(j){const raw=String(j.stage||'').toLowerCase();if(j.completion_date)return'complete';if(j.production_started_date||raw.includes('in production'))return'production';if(raw.includes('final payment')||raw.includes('closeout'))return'closeout';if(j.material_delivery_date||raw.includes('material delivered'))return'delivered';if(j.confirmed_start_date||j.target_start_date||raw==='scheduled')return'scheduled';if(raw.includes('ready to schedule'))return'ready';if(j.material_ordered_date||raw.includes('material ordered'))return'material';if(raw.includes('deposit')||raw.includes('contract'))return'contract';return'awarded';}
function stageLabel(j){return STAGES.find(([k])=>k===stageKey(j))?.[1]||'Awarded';}
function nextStep(j){if(j.production_blocker)return j.production_blocker;if(j.client_communication_needed)return j.client_communication_reason||'Customer update needed';const s=stageKey(j);if(s==='awarded')return j.deposit_status&&String(j.deposit_status).toLowerCase().includes('received')?'Prepare materials / schedule':'Confirm contract and deposit';if(s==='contract')return'Order materials';if(s==='material')return j.confirmed_start_date?'Prepare for start':'Schedule installation';if(s==='ready')return'Set install date';if(s==='scheduled')return j.material_delivery_date?'Confirm delivery / crew':'Confirm materials and crew';if(s==='delivered')return'Start production';if(s==='production')return'Complete work / final inspection';if(s==='complete')return'Final invoice / closeout';return'Close job';}
function attentionReasons(j){const reasons=[];const today=new Date();today.setHours(12,0,0,0);if(j.production_blocker)reasons.push(j.production_blocker);if(j.client_communication_needed)reasons.push(j.client_communication_reason||'Customer contact needed');if(j.client_communication_due_date&&new Date(j.client_communication_due_date+'T12:00:00')<=today)reasons.push('Customer update due');if(stageKey(j)==='awarded'&&!j.confirmed_start_date&&!j.target_start_date){const d=new Date((j.contract_date||j.sale_date||j.created_at||'').slice(0,10)+'T12:00:00');if(!Number.isNaN(d)&&((today-d)/86400000)>=7)reasons.push('No start date');}if(j.production_last_update_at){const d=new Date(j.production_last_update_at);if((Date.now()-d.getTime())/86400000>7)reasons.push('No recent production update');}return [...new Set(reasons)];}
function activeJobs(){return jobs.filter(j=>!j.deleted_at&&!j.archived_at&&!['cancelled','canceled','final / closed','fully paid','closed'].includes(String(j.stage||'').toLowerCase()));}
function filtered(){const q=$('jobSearch').value.trim().toLowerCase(),t=$('jobTypeFilter').value;return activeJobs().filter(j=>(!t||jobType(j)===t)&&(!q||[j.job_number,j.customer_name,j.property_address,j.lead_number,j.stage,j.installer,jobType(j),j.production_notes].join(' ').toLowerCase().includes(q)));}
function card(j){const att=attentionReasons(j);return `<div class="job-card" data-job-id="${esc(j.id)}"><b>${esc(j.job_number||'Job')}</b><div>${esc(j.customer_name||'Unnamed customer')}</div><div class="job-meta">${esc(jobType(j))}</div><div class="job-meta">${j.confirmed_start_date?'Start: '+esc(dateLabel(j.confirmed_start_date)):j.contract_date?'Contract: '+esc(dateLabel(j.contract_date)):''}</div><span class="job-badge ${att.length?'attention-badge':''}">${esc(att[0]||nextStep(j))}</span></div>`;}
function renderTimeline(){const rows=filtered();$('timelineBoard').innerHTML=STAGES.map(([key,label])=>{const group=rows.filter(j=>stageKey(j)===key);return `<div class="stage-col stage-${key}"><div class="stage-head">${label}<small>${group.length} job${group.length===1?'':'s'}</small></div>${group.map(card).join('')||'<div class="job-meta">No jobs</div>'}</div>`}).join('');}
function renderTable(){const rows=filtered();$('jobsTableBody').innerHTML=rows.map(j=>`<tr data-job-id="${esc(j.id)}"><td><b>${esc(j.job_number||'')}</b></td><td>${esc(j.customer_name||'')}</td><td>${esc(jobType(j))}</td><td>${esc(stageLabel(j))}</td><td>${esc(dateLabel(j.confirmed_start_date||j.target_start_date))}</td><td>${esc(j.installer||'')}</td><td>${esc(nextStep(j))}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No active jobs match.</td></tr>';}
function renderAttention(){const rows=filtered().map(j=>({j,reasons:attentionReasons(j)})).filter(x=>x.reasons.length);$('attentionList').innerHTML=rows.length?`<div class="attention-row" style="font-weight:700;background:#eef3f8"><div>Job #</div><div>Customer</div><div>Issue</div><div>Start</div><div>Next step</div></div>`+rows.map(({j,reasons})=>`<div class="attention-row" data-job-id="${esc(j.id)}"><div><b>${esc(j.job_number||'')}</b></div><div>${esc(j.customer_name||'')}</div><div>${esc(reasons.join(' • '))}</div><div>${esc(dateLabel(j.confirmed_start_date||j.target_start_date))}</div><div>${esc(nextStep(j))}</div></div>`).join(''):'<div class="empty">Nothing currently needs attention.</div>';}
function renderCalendar(){const days=Array.from({length:7},(_,i)=>addDays(weekStart,i));$('weekLabel').textContent=`${days[0].toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${days[6].toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`;const rows=[['Material Delivery','material_delivery_date'],['Production Start','confirmed_start_date'],['Expected Completion','expected_completion_date'],['Confirmed Completion','completion_date']];let html='<div class="cal-cell cal-head"></div>'+days.map(d=>`<div class="cal-cell cal-head">${d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</div>`).join('');for(const [label,field] of rows){html+=`<div class="cal-cell cal-head">${label}</div>`;for(const d of days){const events=filtered().filter(j=>sameDay(j[field],d));html+=`<div class="cal-cell">${events.map(j=>`<div class="cal-event" data-job-id="${esc(j.id)}"><b>${esc(j.job_number||'')}</b><br>${esc(j.customer_name||'')}</div>`).join('')}</div>`;}}$('calendarGrid').innerHTML=html;}
function renderAll(){renderTimeline();renderCalendar();renderAttention();renderTable();}
function setView(v){activeView=v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));['timeline','calendar','attention','table'].forEach(x=>$(x+'View').classList.toggle('hidden',x!==v));}
function openJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;$('editJobId').value=j.id;$('jobDialogTitle').textContent=`Job ${j.job_number||''} – ${j.customer_name||''}`;$('editCustomer').value=j.customer_name||'';$('editJobNumber').value=j.job_number||'';$('editInquiryNumber').value=j.lead_number||'';$('editJobType').value=jobType(j);$('editStage').value=stageLabel(j);$('editContractDate').value=iso(j.contract_date);$('editMaterialOrdered').value=iso(j.material_ordered_date);$('editMaterialDelivery').value=iso(j.material_delivery_date);$('editStart').value=iso(j.confirmed_start_date);$('editExpected').value=iso(j.expected_completion_date);$('editCompleted').value=iso(j.completion_date);$('editInstaller').value=j.installer||'';$('editCommDue').value=iso(j.client_communication_due_date);$('editAddress').value=j.property_address||'';$('editBlocker').value=j.production_blocker||'';$('editNotes').value=j.production_notes||'';$('jobDialog').showModal();}
async function saveJob(){const id=$('editJobId').value;const patch={customer_name:$('editCustomer').value.trim(),job_number:$('editJobNumber').value.trim()||null,lead_number:$('editInquiryNumber').value.trim()||null,job_type:$('editJobType').value.trim()||null,primary_category:$('editJobType').value.trim()||null,stage:$('editStage').value,contract_date:$('editContractDate').value||null,material_ordered_date:$('editMaterialOrdered').value||null,material_delivery_date:$('editMaterialDelivery').value||null,confirmed_start_date:$('editStart').value||null,expected_completion_date:$('editExpected').value||null,completion_date:$('editCompleted').value||null,installer:$('editInstaller').value.trim()||null,client_communication_due_date:$('editCommDue').value||null,property_address:$('editAddress').value.trim()||null,production_blocker:$('editBlocker').value.trim()||null,production_notes:$('editNotes').value.trim()||null,updated_at:new Date().toISOString()};if(patch.completion_date){patch.stage='Work Complete';}else if(patch.stage==='Work Complete'){patch.stage='In Production';}const {error}=await db.from('jobs').update(patch).eq('id',id);if(error)return notice(error.message,'error');$('jobDialog').close();await load();notice('Job updated.','success');}
async function load(){const {data,error}=await db.from('jobs').select('*').order('updated_at',{ascending:false}).limit(2000);if(error)return notice(error.message,'error');jobs=data||[];const types=[...new Set(jobs.map(jobType).filter(Boolean))].sort();$('jobTypeFilter').innerHTML='<option value="">All job types</option>'+types.map(t=>`<option>${esc(t)}</option>`).join('');renderAll();}
async function start(){db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const {data}=await db.auth.getSession();if(!data.session){location.href='index.html';return;}await load();}
document.querySelectorAll('.view-tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('jobSearch').oninput=renderAll;$('jobTypeFilter').onchange=renderAll;$('prevWeek').onclick=()=>{weekStart=addDays(weekStart,-7);renderCalendar()};$('nextWeek').onclick=()=>{weekStart=addDays(weekStart,7);renderCalendar()};document.body.addEventListener('click',e=>{const el=e.target.closest('[data-job-id]');if(el)openJob(el.dataset.jobId)});$('saveJobBtn').onclick=saveJob;start();