'use strict';
const cfg=window.BAUER_CONFIG||{};const $=id=>document.getElementById(id);let db=null;let leads=[];let appts=[];let jobs=[];let dragId=null;
const STAGES=[['Appointment','Appointment','p-appointment'],['Estimate Needed','Estimate Needed','p-estneed'],['Estimate Sent','Estimate Sent','p-estsent'],['Follow Up','Follow Up','p-follow'],['Sold','Sold','p-sold'],['Rejected','Rejected','p-rejected']];
const ORDER=Object.fromEntries(STAGES.map((x,i)=>[x[0],i]));
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function notice(t,type=''){const n=$('salesNotice');if(!n)return;n.textContent=t;n.className=`notice ${type}`.trim();if(!t)n.classList.add('hidden');}
function fmtDate(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
function apptFor(id){return appts.filter(a=>a.lead_id===id&&!a.deleted_at&&!['cancelled','canceled','rescheduled'].includes(String(a.appointment_status||'').toLowerCase())).sort((a,b)=>String(b.appointment_at||'').localeCompare(String(a.appointment_at||'')))[0]||null;}
function jobFor(id){return jobs.find(j=>j.lead_id===id&&!j.deleted_at&&!j.contract_canceled_at)||null;}
function stageOf(l){const a=apptFor(l.id),j=jobFor(l.id),saved=String(l.sales_stage||'');if(j)return'Sold';if(['Estimate Needed','Estimate Sent','Follow Up','Sold','Rejected'].includes(saved))return saved;if(!a)return null;const t=new Date(a.appointment_at||0).getTime();if(Number.isFinite(t)&&t<Date.now())return'Estimate Needed';return'Appointment';}
function activeRows(){const q=$('salesSearch').value.trim().toLowerCase(),showClosed=$('showClosed').checked;const cutoff=Date.now()-1000*60*60*24*210;return leads.filter(l=>{if(l.deleted_at||l.archived_at)return false;const stage=stageOf(l);if(!stage)return false;if(!showClosed&&['Sold','Rejected'].includes(stage))return false;const a=apptFor(l.id);const t=new Date(a?.appointment_at||0).getTime();if(Number.isFinite(t)&&t<cutoff&&['Sold','Rejected'].includes(stage))return false;if(q&&!([l.lead_number,l.homeowner_name,l.street_address,l.city,l.phone,l.email,l.product_interest,l.source].join(' ').toLowerCase().includes(q)))return false;return true;});}
function card(l){const a=apptFor(l.id),j=jobFor(l.id);const apptText=a?.appointment_at?fmtDate(a.appointment_at):'';const result=a?.appointment_result||'';const addr=[l.street_address,l.city,l.state,l.zip].filter(Boolean).join(', ');return `<div class="sales-card" draggable="true" data-lead-id="${esc(l.id)}"><b>${esc(l.lead_number?'#'+l.lead_number+' ':'')}${esc(l.homeowner_name||'Unnamed')}</b><div class="meta">${esc(l.product_interest||l.work_category||'')} ${l.source?'• '+esc(l.source):''}</div>${addr?`<div class="meta">${esc(addr)}</div>`:''}${apptText?`<div class="important">Appointment: ${esc(apptText)}</div>`:''}${result?`<div class="meta">Result: ${esc(result)}</div>`:''}${l.estimate_status?`<div class="meta">Estimate: ${esc(l.estimate_status)}</div>`:''}${l.next_follow_up_at?`<div class="important">Follow up: ${esc(fmtDate(l.next_follow_up_at))}</div>`:''}${j?`<div class="important">Job ${esc(j.job_number||'created')}</div>`:''}<div class="card-actions">${l.phone?`<a href="tel:${esc(l.phone)}" data-no-open>Call</a><a href="sms:${esc(l.phone)}" data-no-open>Text</a>`:''}${l.email?`<a href="mailto:${esc(l.email)}" data-no-open>Email</a>`:''}<button type="button" data-open-lead="${esc(l.id)}">Open</button></div></div>`;}
function syncTopScroll(){const top=$('salesTopScroll'),inner=$('salesTopScrollInner'),board=$('salesBoard');if(!top||!inner||!board)return;inner.style.width=board.scrollWidth+'px';top.style.display=board.scrollWidth>board.clientWidth?'block':'none';}
function render(){const rows=activeRows();$('salesBoard').innerHTML=STAGES.map(([key,label,cls])=>{const group=rows.filter(l=>stageOf(l)===key);return `<section class="pipe-col ${cls}" data-stage="${esc(key)}"><div class="pipe-head">${label}<small>${group.length} item${group.length===1?'':'s'}</small></div>${group.map(card).join('')||'<div class="empty">No items</div>'}</section>`}).join('');wireDrag();requestAnimationFrame(syncTopScroll);}
async function saveStage(id,newStage){const l=leads.find(x=>x.id===id);if(!l)return;const old=stageOf(l);if(old===newStage)return;if((ORDER[newStage]??0)<(ORDER[old]??0)&&!confirm(`Move ${l.homeowner_name||'this inquiry'} backward from ${old} to ${newStage}?`)){render();return;}const patch={sales_stage:newStage,updated_at:new Date().toISOString()};if(newStage==='Appointment')patch.lead_status='Appointment Scheduled';if(newStage==='Estimate Needed'){patch.lead_status='Estimate Needed';patch.estimate_status='Needed';}if(newStage==='Estimate Sent'){patch.lead_status='Estimate Sent';patch.estimate_status='Sent';if(!l.estimate_sent_at)patch.estimate_sent_at=new Date().toISOString();}if(newStage==='Follow Up')patch.lead_status='Follow Up';if(newStage==='Sold')patch.lead_status='Sold';if(newStage==='Rejected')patch.lead_status='Rejected';const {error}=await db.from('leads').update(patch).eq('id',id);if(error){notice(error.message,'error');render();return;}Object.assign(l,patch);notice(`${l.homeowner_name||'Inquiry'} moved to ${newStage}.`,'success');render();}
function wireDrag(){document.querySelectorAll('.sales-card').forEach(c=>{c.addEventListener('dragstart',e=>{dragId=c.dataset.leadId;c.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragId);});c.addEventListener('dragend',()=>{dragId=null;c.classList.remove('dragging');document.querySelectorAll('.pipe-col').forEach(x=>x.classList.remove('drop-target'));});});document.querySelectorAll('.pipe-col').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drop-target');});col.addEventListener('dragleave',()=>col.classList.remove('drop-target'));col.addEventListener('drop',e=>{e.preventDefault();col.classList.remove('drop-target');const id=dragId||e.dataTransfer.getData('text/plain');if(id)saveStage(id,col.dataset.stage);});});}
function openLead(id){location.href=`inquiry.html?id=${encodeURIComponent(id)}`;}
function showContext(e,id){const l=leads.find(x=>x.id===id);if(!l)return;const a=apptFor(id),m=$('salesContext');const items=[];items.push(['Open inquiry',()=>openLead(id)]);if(l.phone){items.push(['Call customer',()=>location.href=`tel:${l.phone}`],['Text customer',()=>location.href=`sms:${l.phone}`]);}if(l.email)items.push(['Email customer',()=>location.href=`mailto:${l.email}`]);items.push(['Schedule / edit appointment',()=>openLead(id)]);if(a)items.push(['Record appointment result…',()=>openOutcome(id)]);items.push(['Follow up tomorrow',()=>quickFollow(id,1)],['Follow up next week',()=>quickFollow(id,7)]);items.push(['Copy lead number',()=>navigator.clipboard?.writeText(l.lead_number||'')],['Copy address',()=>navigator.clipboard?.writeText([l.street_address,l.city,l.state,l.zip].filter(Boolean).join(', '))]);m.innerHTML=items.map((x,i)=>`<button type="button" data-mi="${i}">${esc(x[0])}</button>`).join('');m.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{hideContext();items[i][1]();});m.style.display='block';const r=m.getBoundingClientRect();m.style.left=Math.min(e.clientX,innerWidth-r.width-8)+'px';m.style.top=Math.min(e.clientY,innerHeight-r.height-8)+'px';}
function hideContext(){$('salesContext').style.display='none';}
async function quickFollow(id,days){const d=new Date();d.setDate(d.getDate()+days);d.setHours(9,0,0,0);const {error}=await db.from('leads').update({sales_stage:'Follow Up',lead_status:'Follow Up',next_follow_up_at:d.toISOString(),updated_at:new Date().toISOString()}).eq('id',id);if(error)return notice(error.message,'error');const l=leads.find(x=>x.id===id);if(l){l.sales_stage='Follow Up';l.lead_status='Follow Up';l.next_follow_up_at=d.toISOString();}render();notice(`Follow-up set for ${d.toLocaleDateString()}.`,'success');}
function openOutcome(id){$('outcomeLeadId').value=id;$('outcomeNote').value='';$('outcomeDialog').showModal();}
async function saveOutcome(){const id=$('outcomeLeadId').value,a=apptFor(id);if(!a)return notice('No appointment found for this inquiry.','error');const result=$('outcomeResult').value,note=$('outcomeNote').value.trim()||null;const patch={appointment_result:result,appointment_result_note:note,appointment_status:'Completed',updated_at:new Date().toISOString()};const {error}=await db.from('appointments').update(patch).eq('id',a.id);if(error)return notice(error.message,'error');Object.assign(a,patch);let stage='Follow Up',leadPatch={};if(result==='Estimate needed'){stage='Estimate Needed';leadPatch={estimate_status:'Needed',lead_status:'Estimate Needed'};}else if(result==='Estimate sent/given'){stage='Estimate Sent';leadPatch={estimate_status:'Sent',estimate_sent_at:new Date().toISOString(),lead_status:'Estimate Sent'};}else if(result==='Contract signed'){stage='Sold';leadPatch={lead_status:'Sold'};}else if(result==='Not interested'){stage='Rejected';leadPatch={lead_status:'Rejected'};}else if(result==='Reschedule'||result==='Another appointment needed'){stage='Appointment';leadPatch={lead_status:'Scheduling'};}else{leadPatch={lead_status:'Follow Up'};}const {error:le}=await db.from('leads').update({sales_stage:stage,...leadPatch,updated_at:new Date().toISOString()}).eq('id',id);if(le)return notice(le.message,'error');const l=leads.find(x=>x.id===id);if(l)Object.assign(l,{sales_stage:stage,...leadPatch});$('outcomeDialog').close();render();notice('Appointment result saved.','success');}
async function load(){notice('Loading appointments…');const cutoff=new Date(Date.now()-1000*60*60*24*365).toISOString();const ar=await db.from('appointments').select('*').is('deleted_at',null).gte('appointment_at',cutoff).order('appointment_at',{ascending:false}).limit(2500);if(ar.error){notice(`Appointments could not load: ${ar.error.message}`,'error');return;}appts=ar.data||[];const leadIds=[...new Set(appts.map(a=>a.lead_id).filter(Boolean))];if(!leadIds.length){leads=[];jobs=[];render();notice('No linked appointments were found for the pipeline.','error');return;}const lr=await db.from('leads').select('*').in('id',leadIds).is('deleted_at',null).limit(2500);if(lr.error){notice(`Inquiries could not load: ${lr.error.message}`,'error');return;}leads=lr.data||[];const jr=await db.from('jobs').select('id,lead_id,job_number,stage,deleted_at,contract_canceled_at').in('lead_id',leadIds).limit(2500);jobs=jr.error?[]:(jr.data||[]);render();notice('');}
async function start(){db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const {data}=await db.auth.getSession();if(!data.session){location.href='index.html';return;}await load();}
$('salesSearch').oninput=render;$('showClosed').onchange=render;$('refreshSales').onclick=load;$('saveOutcome').onclick=saveOutcome;const top=$('salesTopScroll'),board=$('salesBoard');if(top&&board){let syncing=false;top.addEventListener('scroll',()=>{if(syncing)return;syncing=true;board.scrollLeft=top.scrollLeft;syncing=false;});board.addEventListener('scroll',()=>{if(syncing)return;syncing=true;top.scrollLeft=board.scrollLeft;syncing=false;});}window.addEventListener('resize',syncTopScroll);document.addEventListener('click',e=>{if(!e.target.closest('#salesContext'))hideContext();const open=e.target.closest('[data-open-lead]');if(open){e.preventDefault();openLead(open.dataset.openLead);}});document.addEventListener('contextmenu',e=>{const c=e.target.closest('.sales-card');if(!c)return;e.preventDefault();showContext(e,c.dataset.leadId);});document.addEventListener('keydown',e=>{if(e.key==='Escape')hideContext();});start();