'use strict';
(function(){
 const cfg=window.BAUER_CONFIG||{},$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let db,subs=[],requests=[],jobs=[],selected=null;
 function notice(t,type=''){const n=$('notice');n.textContent=t||'';n.className=`notice ${type}`.trim();if(!t)n.classList.add('hidden');}
 function address(s){return [s.street_address,[s.city,s.state,s.zip].filter(Boolean).join(', ')].filter(Boolean).join(' · ');}
 function renderList(){const q=$('subSearch').value.trim().toLowerCase(),rows=subs.filter(s=>!q||[s.company_name,s.contact_name,address(s)].join(' ').toLowerCase().includes(q));$('subList').innerHTML=rows.length?rows.map(s=>`<button class="sub-row ${selected===s.id?'active':''}" data-sub="${esc(s.id)}"><b>${esc(s.company_name)}</b><div class="muted">${esc(s.contact_name||'No contact name')} · ${esc(address(s)||'No address')}</div>${s.active?'':'<div class="muted">Inactive</div>'}</button>`).join(''):'<div class="empty">No subcontractors match.</div>';}
 function renderDetail(){const s=subs.find(x=>x.id===selected);if(!s)return;const rows=requests.filter(r=>r.subcontractor_id===s.id),byJob=new Map(jobs.map(j=>[j.id,j]));$('subDetail').innerHTML=`<div class="head"><div><h2>${esc(s.company_name)}</h2><div>${esc(address(s)||'No address')}</div><div>${esc(s.contact_name||'No contact / signer')}</div><div class="muted">Retainage: ${Number(s.retainage_percent||0).toFixed(2)}%</div></div><button class="btn" type="button" data-edit-sub="${esc(s.id)}">Edit</button></div><h3>Requests for Payment</h3>${rows.length?rows.map(r=>{const j=byJob.get(r.job_id)||{};return `<div class="payment-row"><div><b>Job ${esc(j.job_number||r.job_number_snapshot||'')}</b><div class="muted">${esc(j.customer_name||r.customer_name_snapshot||'')}</div></div><div>Requisition #${esc(r.requisition_number)}</div><div>${esc(String(r.payment_date||''))}</div><a class="btn small" target="_blank" href="payment-request-print.html?id=${encodeURIComponent(r.id)}">Print</a></div>`;}).join(''):'<div class="empty">No Requests for Payment have been created for this subcontractor.</div>'}`;}
 async function load(){notice('Loading subcontractors…');const [s,r,j]=await Promise.all([db.from('subcontractors').select('*').order('company_name'),db.from('subcontractor_payment_requests').select('*').order('payment_date',{ascending:false}),db.from('jobs').select('id,job_number,customer_name').is('deleted_at',null)]);if(s.error||r.error||j.error)return notice((s.error||r.error||j.error).message,'error');subs=s.data||[];requests=r.data||[];jobs=j.data||[];if(selected&&!subs.some(x=>x.id===selected))selected=null;renderList();if(selected)renderDetail();notice('');}
 function edit(row=null){const s=row||{};$('subDialogTitle').textContent=row?'Edit Subcontractor':'Add Subcontractor';$('subId').value=s.id||'';$('subCompany').value=s.company_name||'';$('subStreet').value=s.street_address||'';$('subCity').value=s.city||'';$('subState').value=s.state||'SC';$('subZip').value=s.zip||'';$('subContact').value=s.contact_name||'';$('subRetainage').value=s.retainage_percent??0;$('subActive').checked=row?s.active!==false:true;$('subDialog').showModal();}
 async function save(){const id=$('subId').value,row={company_name:$('subCompany').value.trim(),street_address:$('subStreet').value.trim()||null,city:$('subCity').value.trim()||null,state:$('subState').value.trim().toUpperCase()||null,zip:$('subZip').value.trim()||null,contact_name:$('subContact').value.trim()||null,retainage_percent:Number($('subRetainage').value||0),active:$('subActive').checked,updated_at:new Date().toISOString()};if(!row.company_name)return notice('Company name is required.','error');const result=id?await db.from('subcontractors').update(row).eq('id',id).select('*').single():await db.from('subcontractors').insert(row).select('*').single();if(result.error)return notice(result.error.message,'error');selected=result.data.id;$('subDialog').close();await load();notice(id?'Subcontractor updated.':'Subcontractor added.','success');}
 async function start(){try{db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const a=await db.auth.getSession();if(!a.data.session){location.href='index.html';return;}await load();}catch(e){notice(e.message||String(e),'error');}}
 $('addSubBtn').onclick=()=>edit();$('saveSubBtn').onclick=save;$('refreshBtn').onclick=load;$('subSearch').oninput=renderList;$('subList').onclick=e=>{const b=e.target.closest('[data-sub]');if(b){selected=b.dataset.sub;renderList();renderDetail();}};$('subDetail').onclick=e=>{const b=e.target.closest('[data-edit-sub]');if(b)edit(subs.find(x=>x.id===b.dataset.editSub));};start();
})();
