'use strict';
const cfg=window.BAUER_CONFIG||{};const $=id=>document.getElementById(id);let db=null;let session=null;const p=new URLSearchParams(location.search);const existingContactId=p.get('contact')||'';
const v=id=>String($(id)?.value||'').trim();const n=id=>v(id)||null;const b=id=>v(id)==='Yes'?true:v(id)==='No'?false:null;
function today(){return new Date().toLocaleDateString('en-CA',{timeZone:'America/New_York'});}function show(t,type=''){const x=$('notice');x.textContent=t;x.className=`notice ${type}`.trim();}
async function nextNumber(){const [lr,sr]=await Promise.all([db.from('leads').select('lead_number').is('deleted_at',null).not('lead_number','is',null).limit(10000),db.from('settings').select('value').eq('setting','Lead Sheet Highest Number').limit(1)]);if(lr.error)throw lr.error;let max=0;const used=new Set();for(const r of lr.data||[]){const s=String(r.lead_number||'').trim();if(/^\d+$/.test(s)){const x=Number(s);used.add(x);if(x>max)max=x;}}if(!sr.error&&sr.data?.length){const floor=Number(sr.data[0].value);if(Number.isFinite(floor)&&floor>max)max=floor;}let x=max+1;while(used.has(x))x++;return String(x);}
async function loadContact(){if(!existingContactId)return;const {data,error}=await db.from('contacts').select('*').eq('id',existingContactId).single();if(error)return;$('#homeownerName').value=data.name||'';$('#phone').value=data.phone||'';$('#email').value=data.email||'';$('#street').value=data.street_address||'';$('#city').value=data.city||'';$('#state').value=data.state||'SC';$('#zip').value=data.zip||'';}
async function suggest(){try{const x=await nextNumber();$('#leadSuggestion').innerHTML=`Suggested next inquiry #: <b>${x}</b> <button type="button" class="btn small" id="useSuggested">Use ${x}</button>`;$('#useSuggested').onclick=()=>{$('#leadNumber').value=x;};}catch(e){$('#leadSuggestion').textContent='Could not suggest a number.';}}
async function findExistingContact(row){if(existingContactId){const {data}=await db.from('contacts').select('*').eq('id',existingContactId).maybeSingle();if(data)return data;}const matches=new Map();if(row.email){const q=await db.from('contacts').select('*').ilike('email',row.email).limit(10);for(const x of q.data||[])matches.set(x.id,x);}if(row.phone){const q=await db.from('contacts').select('*').eq('phone',row.phone).limit(10);for(const x of q.data||[])matches.set(x.id,x);}const exact=[...matches.values()];return exact.length===1?exact[0]:null;}
async function save(e){e.preventDefault();const btn=$('saveBtn');btn.disabled=true;$('#status').textContent='Saving…';try{const name=v('homeownerName')||[v('firstName'),v('lastName')].filter(Boolean).join(' ');if(!name)throw new Error('Name / Company is required.');const contactRow={name,phone:n('phone'),email:n('email'),street_address:n('street'),city:n('city'),state:n('state'),zip:n('zip')};let contact=await findExistingContact(contactRow);if(contact){const {data,error}=await db.from('contacts').update({...contactRow,updated_at:new Date().toISOString()}).eq('id',contact.id).select('*').single();if(error)throw error;contact=data;}else{const {data,error}=await db.from('contacts').insert(contactRow).select('*').single();if(error)throw error;contact=data;}
const leadRow={contact_id:contact.id,lead_number:n('leadNumber'),homeowner_name:name,first_name:n('firstName'),last_name:n('lastName'),spouse_name:n('spouseName'),phone:n('phone'),phone_secondary:n('phoneSecondary'),email:n('email'),street_address:n('street'),city:n('city'),state:n('state'),zip:n('zip'),subdivision:n('subdivision'),directions:n('directions'),mailing_street_address:n('mailingStreet'),mailing_city:n('mailingCity'),mailing_state:n('mailingState'),mailing_zip:n('mailingZip'),insurance_related:b('insuranceRelated'),insurance_company:n('insuranceCompany'),shingle_age:n('shingleAge'),desired_work_timing:n('desiredWorkTiming'),roof_layers:n('roofLayers'),current_leak:b('currentLeak'),current_leak_location:n('currentLeakLocation'),prior_leak:b('priorLeak'),prior_leak_location:n('priorLeakLocation'),home_type:n('homeType'),roof_pitch:n('roofPitch'),payment_plan:n('paymentPlan'),source:n('source'),lead_source_secondary:n('sourceSecondary'),work_category:n('workCategory'),product_interest:n('productInterest'),product_description:n('productDescription'),notes:n('notes'),taken_by:n('takenBy'),inquiry_taken_by:n('takenBy'),assigned_to:n('assignedTo'),lead_status:'Appointment Wanted',lead_date:n('leadDate')||today(),import_source:'Contact Inquiry'};const {data:lead,error}=await db.from('leads').insert(leadRow).select('*').single();if(error)throw error;location.href=`inquiry.html?id=${encodeURIComponent(lead.id)}&contact=${encodeURIComponent(contact.id)}`;}catch(err){show(err.message||String(err),'error');$('#status').textContent='';btn.disabled=false;}}
async function start(){db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const a=await db.auth.getSession();session=a.data.session;if(!session){location.href='index.html';return;}$('#leadDate').value=today();await loadContact();await suggest();$('#form').addEventListener('submit',save);}
start();