-- Shared BRO editing for the explicitly approved team; personal workspace stays personal.
create schema if not exists bro_private;
revoke all on schema bro_private from public, anon;
grant usage on schema bro_private to authenticated;
create table bro_private.team_access (
  email text primary key check (email=lower(email)),
  workspace_owner uuid not null references auth.users(id),
  display_name text not null,
  active boolean not null default true
);
alter table bro_private.team_access enable row level security;
revoke all on bro_private.team_access from public, anon, authenticated;
insert into bro_private.team_access(email,workspace_owner,display_name)
select members.email,u.id,members.name from auth.users u
cross join (values ('evebauer@bauerroofs.com','Eve'),('jbauer@bauerroofs.com','Dad'),('rbauer@bauerroofs.com','Roy')) members(email,name)
where lower(u.email)='evebauer@bauerroofs.com' and u.email_confirmed_at is not null;
do $$ begin
 if (select count(*) from bro_private.team_access)<>3 then raise exception 'Confirmed workspace owner not found'; end if;
end $$;

-- Definer is only for reading the private membership/Auth lookup, never customer data.
create function bro_private.workspace_owner() returns uuid
language sql stable security definer set search_path='' as $$
 select coalesce((select m.workspace_owner from bro_private.team_access m
 join auth.users u on lower(u.email)=m.email
 where u.id=auth.uid() and u.email_confirmed_at is not null
 and (u.banned_until is null or u.banned_until<now()) and m.active),auth.uid());
$$;
revoke all on function bro_private.workspace_owner() from public,anon;
grant execute on function bro_private.workspace_owner() to authenticated;

create function bro_private.canonical_business_owner() returns trigger
language plpgsql security invoker set search_path='' as $$
begin
 if auth.uid() is not null and (new.owner_id is null or new.owner_id=auth.uid()) then
   new.owner_id:=bro_private.workspace_owner();
 end if;
 return new;
end $$;
revoke all on function bro_private.canonical_business_owner() from public,anon;

do $$ declare t text; p record; begin
 foreach t in array array['contacts','leads','jobs','prospects','appointments','phone_messages','communications','sales_communications','contact_communications','job_communications','job_work_items','payments','job_payments','job_insurance','job_documents','job_document_links','job_contract_addendums','job_closeout_items','warranty_callbacks','appointment_notification_queue','contact_automation_queue','sops','workflows','workflow_steps','projects'] loop
   execute format('create policy bro_team_edit on public.%I for all to authenticated using (owner_id=(select bro_private.workspace_owner())) with check (owner_id=(select bro_private.workspace_owner()))',t);
   execute format('create trigger aaa_bro_business_owner before insert on public.%I for each row execute function bro_private.canonical_business_owner()',t);
 end loop;
 -- Archives remain preserved, but team members can open linked history.
 foreach t in array array['marketsharp_contacts','marketsharp_inquiries','marketsharp_appointments','marketsharp_jobs'] loop
   execute format('create policy bro_team_archive_read on public.%I for select to authenticated using (imported_by=(select bro_private.workspace_owner()))',t);
 end loop;
 -- A subtask must be accessed through a task visible to the current login.
 drop policy task_subtasks_authenticated_all on public.task_subtasks;
 create policy task_subtasks_parent_access on public.task_subtasks for all to authenticated
 using (exists(select 1 from public.tasks t where t.id=task_id))
 with check (exists(select 1 from public.tasks t where t.id=task_id));
 -- Existing permissive calendar-insert lead policy must not defeat ownership checks.
 drop policy leads_authenticated_insert_from_calendar on public.leads;
 -- Outcome access follows inquiry access, including approved team members.
 for p in select * from pg_policies where schemaname='public' and tablename in ('roy_appointment_outcomes','roy_estimate_updates') loop
   execute format('alter policy %I on public.%I using (%s)%s',p.policyname,p.tablename,
    replace(p.qual,'l.owner_id = ( SELECT auth.uid() AS uid)','l.owner_id = ( SELECT bro_private.workspace_owner())'),
    case when p.with_check is null then '' else ' with check ('||replace(p.with_check,'l.owner_id = ( SELECT auth.uid() AS uid)','l.owner_id = ( SELECT bro_private.workspace_owner())')||')' end);
 end loop;
end $$;
-- Business-triggered follow-up tasks retain their original assignee/owner.
-- Today filters its task list by the signed-in user; team editing can still create
-- the office follow-up generated by a production or appointment change.
create policy bro_team_tasks on public.tasks for all to authenticated
using (owner_id=(select bro_private.workspace_owner()))
with check (owner_id=(select bro_private.workspace_owner()));
notify pgrst,'reload schema';
